### ISSUE TITLE
Changes to entity are only saved when closing popup

### ISSUE THREAD

**Issue by sigurdcarlsen** [theborderland/map#11]
When a user edits entity info they might expect the entity to be saved when clicking "Done" in the bottom left corner, or when clicking "Ok!". 
From what I can tell, a revision of the entity is only uploaded when the entity popup is closed. Unaware users might spend a long time editing a description, then clicking Ok! and "done" and exiting the page only to realise later that nothing was saved.

An easy solution would be to notify users of this behavior under the "How to use the Placement Tool" section on the instructions page.

**Comment by sigurdcarlsen** [comment]
Also i guess we could tell users that the descriptions are saved the moment they close the popup. If they are unaware of this they might acidentally save something they did not intend to.

**Comment by lyret** [comment]
Great!

**Comment by sigurdcarlsen** [comment]
Would love to but I guess I need to be added as a maintainer first or some other role?

**Comment by sigurdcarlsen** [comment]
I added a "Saved" popup, in my fork. I think this could be a nice way for users to know that their changes have been saved.

**Comment by lyret** [comment]
This is resolved in the pull request, great work!
