### ISSUE TITLE
Make sure that area names are displayed on the map

### ISSUE THREAD

**Issue by lyret** [theborderland/map#21]
Both for neighborhoods and for kvarters. Should be two different layers

https://miro.com/app/board/uXjVKWcyTqQ=/

**Comment by sigurdcarlsen** [comment]
I am working on adding neighbourhood, plaza and quarters names tot he map

**Comment by sigurdcarlsen** [comment]
Instead of drawing text using polygons, as it seems was done last year, I decided to display the area names using svg text instead.
Check it out in the branch text-to-svg and tell me what you think. Colors, fonts size and the grouping of the different layers is totally up for debate.
@lyret

**Comment by lyret** [comment]
Closing issues that are resolved in the pull request, for status clarity (not merging yet to prevent gh pages deploy)
