### ISSUE TITLE
Performance is pretty slow

### ISSUE THREAD

**Issue by rulkens** [theborderland/map#7]
Hi all, I'm using the map extensively and with all the camps now filled in, the loading of data every time has come pretty much to a halt. Looking at performance, the culprit is the `_getTotalAreaOfOverlappingEntities` function. I could have a look at optimizing this, if I know what branch is currently deployed. Can someone tell me?

**Comment by TimGremalm** [comment]
Yes it's problematic. It would be great if you could have a look at it.
Next year we'll probably rethink this bit. Maybe do the calculation on the backend while saving and store the validated result. Or do the calculation in a thread.

The main branch is the one that we have deployed.

Would you like to join the placement team next year?

**Comment by lyret** [comment]
Closing this to keep any discussions going in #10 instead
